package com.squareup.workflow1.buildsrc.dokka

import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import org.gradle.kotlin.dsl.support.normaliseLineSeparators
import java.io.File

@CacheableTask
abstract class DisableOldDokkaAutoFormatTask : DefaultTask() {
  init {
    group = "dokka versioning"
    description = "writes a simple .editorconfig which disables all formatting in the directory"
  }

  @get:OutputFile
  abstract val editorConfig: RegularFileProperty

  @TaskAction
  fun writeEditorConfig() {
    val file = editorConfig.get().asFile
    file.parentFile.mkdirs()

    val content = """
      # Disable auto-format for any files copied to /old-dokka/
      # These are generated by Dokka and the formatting is all over the place,
      # so an auto-format like the one from the IDE commit dialog can create a huge diff.
      # This behavior is also disabled by adding the following to the root .editorconfig:
      #
      # [old-dokka/**]
      # ij_formatter_enabled = false
      #
      root = true
      [*]
      ij_formatter_enabled = false
    """.trimIndent()
      .normaliseLineSeparators()

    checkExistingContent(file = file, expected = content)

    file.writeText(content)
  }

  private fun checkExistingContent(
    file: File,
    expected: String
  ) {

    if (!file.exists()) return

    val actual = file.readText()
      .lines()
      .map { it.trim() }
      .joinToString("\n")
      .trim()
      .normaliseLineSeparators()

    check(actual == expected) {
      val actualIndented = actual.lines().joinToString("\n\t", "\t")
      val expectedIndented = expected.lines().joinToString("\n\t", "\t")

      """
      |The old-dokka/.editorconfig file exists, but with unexpected content.
      |
      |file: file://${file.path}
      |
      |expected content:
      |
      |$expectedIndented
      |
      |actual content:
      |
      |$actualIndented
      |
      |If the existing file is valid, update this task's definition.
      """.replaceIndentByMargin()
    }
  }
}
